/**
 * 아이콘 검색용 로케일 별칭 → SF Symbol 영문 토큰.
 * 큐레이션(~1000) 카탈로그 스템 기준으로 생성·유지.
 */
export const CUSTOM_FLOW_ICON_SEARCH_ALIASES: Record<string, readonly string[]> = {
  "家": ["house"],
  "가계부": ["banknote", "chart", "creditcard", "wonsign", "yensign"],
  "가방": ["bag", "duffle"],
  "가습기": ["humidifier"],
  "가족": ["holdinghands", "person"],
  "ホーム": ["house"],
  "홈": ["house"],
  "友達": ["person"],
  "친구": ["person"],
  "バッテリー": ["bolt"],
  "電池": ["bolt"],
  "배터리": ["bolt"],
  "충전": ["bolt"],
  "充電": ["bolt"],
  "각도": ["angled"],
  "角度": ["angled"],
  "강아지": ["dog"],
  "加湿器": ["humidifier"],
  "개발": ["laptopcomputer", "terminal"],
  "開く": ["open"],
  "거북": ["tortoise"],
  "鍵": ["key"],
  "건강": ["brain", "cross", "figure", "heart", "lungs"],
  "건물": ["building"],
  "建物": ["building"],
  "걷기": ["walk"],
  "검색": ["magnifyingglass"],
  "게임": ["gamecontroller"],
  "犬": ["dog"],
  "겹침": ["stack"],
  "경고": ["exclamationmark"],
  "경기장": ["field"],
  "경로": ["path"],
  "更新": ["clockwise"],
  "계단": ["stair", "stairs"],
  "階段": ["stair", "stairs"],
  "고강도": ["highintensity"],
  "고양이": ["cat"],
  "골프": ["golf"],
  "곰돌이": ["teddybear"],
  "공간음향": ["spatialaudio"],
  "空間オーディオ": ["spatialaudio"],
  "공구": ["wrench"],
  "공기": ["carbon"],
  "공부": ["book", "graduationcap", "pencil"],
  "공연": ["theatermask"],
  "高強度": ["highintensity"],
  "광선": ["rays"],
  "光線": ["rays"],
  "絞り": ["aperture"],
  "구름": ["cloud"],
  "그리기": ["draw"],
  "그림": ["artframe"],
  "근력": ["dumbbell", "strengthtraining"],
  "筋トレ": ["dumbbell", "strengthtraining"],
  "글": ["text"],
  "글쓰기": ["character", "pencil", "text"],
  "給油": ["fuelpump"],
  "旗": ["flag"],
  "기름": ["oilcan"],
  "기차": ["train"],
  "기타": ["guitars"],
  "길": ["path"],
  "깃발": ["flag"],
  "나무": ["tree"],
  "낙상": ["fall"],
  "낚시": ["fishing"],
  "날씨": ["cloud", "rain", "snow", "sun", "thermometer"],
  "낮잠": ["moon", "sofa", "zzz"],
  "냉장고": ["refrigerator"],
  "넘어짐": ["fall"],
  "노트북": ["laptopcomputer"],
  "농구": ["basketball"],
  "뇌": ["brain"],
  "눈": ["eye", "snow"],
  "눈송이": ["snowflake"],
  "다이아": ["diamond"],
  "닫기": ["xmark"],
  "닫힘": ["closed"],
  "달": ["moon"],
  "달러": ["dollarsign"],
  "달력": ["calendar"],
  "달리기": ["run"],
  "大雨": ["heavyrain"],
  "대중교통": ["bus", "train", "tram"],
  "댄스": ["dance"],
  "더보기": ["ellipsis"],
  "더위": ["heat"],
  "덤벨": ["dumbbell"],
  "道": ["path"],
  "도움말": ["questionmark"],
  "도착": ["arrival"],
  "到着": ["arrival"],
  "독서": ["book"],
  "돈": ["dollarsign", "wonsign", "yensign"],
  "동작": ["motion"],
  "動画": ["video"],
  "등산": ["hiking"],
  "登山": ["hiking"],
  "라켓": ["racket"],
  "라켓볼": ["racquetball"],
  "라크로스": ["lacrosse"],
  "冷蔵庫": ["refrigerator"],
  "러닝": ["figure.run", "run"],
  "러닝머신": ["treadmill"],
  "럭비": ["rugby"],
  "레슬링": ["wrestling"],
  "레이싱": ["checkered"],
  "로잉": ["rower", "rowing"],
  "롤러": ["rolling"],
  "料理": ["frying"],
  "루블": ["rublesign"],
  "루틴": ["calendar", "repeat"],
  "루피": ["indianrupeesign"],
  "六角形": ["hexagon"],
  "리워드": ["rewards"],
  "立つ": ["stand"],
  "마이너스": ["minus"],
  "마이크": ["mic", "microphone"],
  "마주보기": ["facing"],
  "막대": ["bar"],
  "말풍선": ["bubble"],
  "맑음": ["sun"],
  "머그": ["mug"],
  "먼지": ["dust"],
  "메달": ["medal"],
  "메모": ["note"],
  "메시지": ["message"],
  "메일": ["mail"],
  "명상": ["brain", "mind", "moon"],
  "瞑想": ["mind"],
  "모래시계": ["hourglass"],
  "木": ["tree"],
  "目": ["eye"],
  "목록": ["list"],
  "목표": ["checkmark", "flag"],
  "몸": ["body"],
  "몸무게": ["scalemass"],
  "猫": ["cat"],
  "描く": ["draw"],
  "霧": ["fog"],
  "무술": ["arts", "martial"],
  "武術": ["martial"],
  "霧雨": ["drizzle"],
  "무지개": ["rainbow"],
  "문서": ["doc", "document", "plaintext", "richtext"],
  "문자": ["character"],
  "文字": ["character"],
  "물": ["water"],
  "물고기": ["fish"],
  "물마시기": ["cup", "drop", "waterbottle"],
  "물방울": ["drop"],
  "물병": ["waterbottle"],
  "물주기": ["sprinkler"],
  "미세먼지": ["haze"],
  "미식축구": ["american", "football"],
  "바": ["bar"],
  "바구니": ["basket"],
  "바람": ["wind"],
  "바레": ["barre"],
  "雹": ["hail"],
  "반려동물": ["cat", "dog", "pawprint", "tortoise"],
  "반복": ["clockwise", "repeat"],
  "반짝": ["sparkles"],
  "발레": ["barre"],
  "발자국": ["pawprint"],
  "밤": ["moon"],
  "배구": ["volleyball"],
  "배드민턴": ["badminton"],
  "버스": ["bus", "doubledecker"],
  "번개": ["bolt"],
  "별": ["star"],
  "병원": ["cross", "ivfluid", "medical", "stethoscope"],
  "보상": ["rewards"],
  "보안": ["shield"],
  "服": ["dress"],
  "복근": ["core"],
  "복싱": ["boxing"],
  "本": ["book", "books"],
  "볼링": ["bowling"],
  "棒": ["bar"],
  "封筒": ["envelope"],
  "体": ["body"],
  "体操": ["gymnastics"],
  "体重計": ["scalemass"],
  "불": ["flame"],
  "붓": ["paintbrush"],
  "뷰파인더": ["viewfinder"],
  "비": ["cloud", "drizzle", "heavyrain", "rain"],
  "비전프로": ["vision"],
  "비트코인": ["bitcoinsign"],
  "비행기": ["airplane"],
  "飛行機": ["airplane"],
  "氷": ["ice"],
  "빛": ["rays"],
  "빨래": ["washer"],
  "빼기": ["minus"],
  "사교댄스": ["socialdance"],
  "社交ダンス": ["socialdance"],
  "사냥": ["hunting"],
  "사람": ["figure", "person"],
  "仕事": ["briefcase"],
  "砂時計": ["hourglass"],
  "사진": ["camera", "photo"],
  "削除": ["minus"],
  "산": ["mountain"],
  "傘": ["umbrella"],
  "山": ["mountain"],
  "산장": ["lodge"],
  "三角": ["triangle"],
  "삼각형": ["triangle"],
  "箱": ["box"],
  "상자": ["box"],
  "새": ["bird"],
  "새로고침": ["clockwise"],
  "생각": ["brain", "lightbulb"],
  "샤워": ["shower"],
  "서기": ["stand"],
  "서류": ["document"],
  "書類": ["doc", "document"],
  "서류가방": ["briefcase"],
  "서비스": ["service"],
  "서핑": ["surfing"],
  "선": ["line"],
  "線": ["line"],
  "선물": ["gift"],
  "雪": ["snow"],
  "설거지": ["fork"],
  "설정": ["gear", "gearshape"],
  "設定": ["gear", "gearshape"],
  "雪の結晶": ["snowflake"],
  "星": ["star"],
  "暑さ": ["heat"],
  "세계": ["globe"],
  "세탁": ["washer"],
  "세탁기": ["washer"],
  "洗濯機": ["washer"],
  "셔터": ["shutter"],
  "소파": ["sofa"],
  "소프트볼": ["softball"],
  "손": ["hand", "hands"],
  "손들기": ["raised"],
  "손바닥": ["palm"],
  "손잡기": ["holdinghands"],
  "손흔들기": ["wave"],
  "쇼핑": ["bag", "basket", "cart"],
  "手": ["hand", "hands"],
  "水": ["water"],
  "수구": ["waterpolo"],
  "水球": ["waterpolo"],
  "수리": ["wrench"],
  "수면": ["bed", "moon", "zzz"],
  "睡眠": ["zzz"],
  "수액": ["ivfluid"],
  "수영": ["pool", "swim", "water"],
  "水泳": ["pool", "swim"],
  "水滴": ["drop"],
  "水筒": ["waterbottle"],
  "숙소": ["lodge"],
  "순서": ["sequence"],
  "手のひら": ["palm"],
  "狩り": ["hunting"],
  "手をつなぐ": ["holdinghands"],
  "스노보드": ["snowboarding"],
  "스케이트": ["skating"],
  "스케이트보드": ["skateboarding"],
  "스쿼시": ["squash"],
  "스키": ["skiing"],
  "스택": ["stack"],
  "스테레오": ["stereo"],
  "스텝퍼": ["stepper"],
  "스트레칭": ["flexibility", "yoga"],
  "스포츠": ["basketball", "figure", "soccerball", "sports", "sportscourt", "tennis"],
  "스프링클러": ["sprinkler"],
  "스피커": ["hifispeaker", "speaker"],
  "습도": ["humidity"],
  "승마": ["equestrian"],
  "시계": ["clock"],
  "時計": ["clock"],
  "시퀀스": ["sequence"],
  "식사": ["fork", "frying", "knife"],
  "食事": ["fork"],
  "신문": ["columns", "newspaper"],
  "新聞": ["newspaper"],
  "신체": ["body"],
  "신호": ["signal"],
  "信号": ["signal"],
  "실내": ["indoor"],
  "실안개": ["haze"],
  "室内": ["indoor"],
  "싫어요": ["thumbsdown"],
  "심전도": ["waveform"],
  "쓰레기": ["trash"],
  "쓰레기통": ["trash"],
  "아이": ["child"],
  "아이디어": ["lightbulb", "sparkles"],
  "아이스": ["ice"],
  "아이클라우드": ["icloud"],
  "안개": ["fog"],
  "안전벨트": ["seatbelt"],
  "앉기": ["seated"],
  "알람": ["alarm"],
  "알림": ["alarm", "bell"],
  "알약": ["pill", "pills"],
  "암호화폐": ["bitcoinsign"],
  "액자": ["artframe"],
  "額縁": ["artframe"],
  "야구": ["baseball"],
  "野球": ["baseball"],
  "야외": ["outdoor"],
  "약": ["cross", "medical", "pill", "pills"],
  "양궁": ["archery"],
  "魚": ["fish"],
  "언어": ["character"],
  "얼음": ["ice"],
  "에어백": ["airbag"],
  "에어플레이": ["airplay"],
  "엔": ["yensign"],
  "円": ["yensign"],
  "엔화": ["yensign"],
  "여행": ["airplane", "map", "suitcase"],
  "여행가방": ["suitcase"],
  "연결": ["connection"],
  "연극": ["theatermask"],
  "演劇": ["theatermask"],
  "연필": ["pencil"],
  "鉛筆": ["pencil"],
  "열": ["heat"],
  "열림": ["open"],
  "열쇠": ["key"],
  "葉": ["leaf"],
  "영상": ["film", "play", "video"],
  "영화": ["film", "play", "tv"],
  "映画": ["film"],
  "예술": ["arts"],
  "오븐": ["oven"],
  "屋外": ["outdoor"],
  "온도": ["degreesign"],
  "온도계": ["thermometer"],
  "옷": ["dress", "suit"],
  "와이드": ["wide"],
  "와이파이": ["wifi"],
  "와인": ["wineglass"],
  "완료": ["checkmark"],
  "요가": ["yoga"],
  "요리": ["cooktop", "fork", "frying", "oven", "refrigerator"],
  "요트": ["sailing"],
  "雨": ["rain"],
  "우박": ["hail"],
  "우산": ["umbrella"],
  "雲": ["cloud"],
  "운동": ["basketball", "dumbbell", "figure", "soccer", "soccerball", "sportscourt", "tennis", "training"],
  "運動": ["figure"],
  "운동복": ["formfitting"],
  "운동장": ["sportscourt"],
  "운전": ["car", "steeringwheel"],
  "運転": ["steeringwheel"],
  "움직임": ["motion"],
  "워치": ["applewatch", "digitalcrown"],
  "원": ["wonsign"],
  "원반": ["disc"],
  "원화": ["wonsign"],
  "月": ["moon"],
  "웨이트": ["dumbbell", "strengthtraining"],
  "웹": ["web"],
  "위안": ["chineseyuanrenminbisign"],
  "위안화": ["chineseyuanrenminbisign"],
  "위치": ["mappin"],
  "윈드실드": ["windshield"],
  "유로": ["eurosign"],
  "유리": ["windshield"],
  "유산소": ["cardio"],
  "有酸素": ["cardio"],
  "육각형": ["hexagon"],
  "肉球": ["pawprint"],
  "육상": ["track"],
  "은행": ["bank"],
  "銀行": ["bank"],
  "音符": ["note"],
  "음식": ["cup", "fork", "frying"],
  "음악": ["music"],
  "음표": ["note"],
  "音楽": ["music"],
  "응급": ["cross"],
  "의료": ["medical"],
  "이산화탄소": ["carbon"],
  "二酸化炭素": ["carbon"],
  "이슬비": ["drizzle"],
  "人": ["person"],
  "인물": ["bust"],
  "人物": ["bust"],
  "人民元": ["chineseyuanrenminbisign"],
  "인용": ["quote"],
  "引用": ["quote"],
  "인터넷": ["web"],
  "인터벌": ["highintensity", "intervaltraining"],
  "인형": ["teddybear"],
  "일기": ["book", "note", "pencil"],
  "일립티컬": ["elliptical"],
  "일시정지": ["pause"],
  "一時停止": ["pause"],
  "일출": ["horizon"],
  "잎": ["leaf"],
  "자": ["ruler"],
  "子供": ["child"],
  "자동": ["automatic"],
  "自動": ["automatic"],
  "자동차": ["car"],
  "자르기": ["crop"],
  "자막": ["captions"],
  "字幕": ["captions"],
  "자전거": ["bicycle", "cycle"],
  "잠": ["zzz"],
  "잠금": ["lock"],
  "장바구니": ["cart"],
  "장보기": ["basket", "cart"],
  "自転車": ["bicycle", "cycle"],
  "재생": ["play"],
  "再生": ["play"],
  "財布": ["bifold", "wallet"],
  "電車": ["train", "tram"],
  "전파": ["signal"],
  "전화": ["phone"],
  "電話": ["phone"],
  "切り抜き": ["crop"],
  "점": ["point"],
  "점선": ["dotted"],
  "点線": ["dotted"],
  "점자": ["braille"],
  "点字": ["braille"],
  "点滴": ["ivfluid"],
  "接続": ["connection"],
  "定規": ["ruler"],
  "정리": ["folder", "tray"],
  "정보": ["info"],
  "情報": ["info"],
  "정장": ["suit"],
  "鳥": ["bird"],
  "조깅": ["run", "walk"],
  "조리개": ["aperture"],
  "조명": ["led"],
  "졸업": ["graduationcap"],
  "卒業": ["graduationcap"],
  "좋아요": ["thumbsup"],
  "釣り": ["fishing"],
  "繰り返し": ["repeat"],
  "座る": ["seated"],
  "주유소": ["fuelpump"],
  "주의": ["exclamationmark"],
  "注意": ["exclamationmark"],
  "줄넘기": ["jumprope"],
  "走る": ["run"],
  "지갑": ["bifold", "wallet"],
  "지구": ["globe"],
  "地球": ["globe"],
  "지도": ["map"],
  "지평선": ["horizon"],
  "地平線": ["horizon"],
  "지폐": ["banknote"],
  "紙幣": ["banknote"],
  "지하철": ["train", "tram"],
  "진눈깨비": ["sleet"],
  "진동": ["haptics"],
  "질문": ["questionmark"],
  "집": ["house"],
  "집중": ["brain", "eye", "timer"],
  "地図": ["map"],
  "차": ["cup", "mug"],
  "車": ["car"],
  "차트": ["chart"],
  "착륙": ["landed"],
  "着陸": ["landed"],
  "책": ["book", "books", "pages"],
  "청진기": ["stethoscope"],
  "체육관": ["gym"],
  "체조": ["gymnastics"],
  "체중": ["scalemass"],
  "체중계": ["scalemass"],
  "체크": ["checkmark"],
  "체크무늬": ["checkered"],
  "초인종": ["doorbell"],
  "촬영": ["viewfinder"],
  "추가": ["append", "plus"],
  "追加": ["append", "plus"],
  "축구": ["figure.soccer", "soccer", "soccerball"],
  "축하": ["party"],
  "출근": ["briefcase", "building", "bus", "car", "tram"],
  "출발": ["departure"],
  "출입": ["pass"],
  "出発": ["departure"],
  "춤": ["dance"],
  "취미": ["camera", "gamecontroller", "music", "paint", "theatermask"],
  "취소": ["xmark"],
  "취침": ["bed", "moon", "zzz"],
  "吹き出し": ["bubble"],
  "측광": ["metering"],
  "測光": ["metering"],
  "측정": ["ruler"],
  "침대": ["bed"],
  "카드": ["card", "creditcard"],
  "카메라": ["aperture", "camera"],
  "칼": ["knife"],
  "칼럼": ["columns"],
  "커피": ["cup", "mug", "saucer"],
  "컬링": ["curling"],
  "컴퓨터": ["desktopcomputer"],
  "컵": ["cup"],
  "코딩": ["chevron.left.forwardslash", "desktopcomputer", "terminal"],
  "코어": ["core"],
  "쿨다운": ["cooldown"],
  "쿨쿨": ["zzz"],
  "크라운": ["digitalcrown"],
  "크로스핏": ["mixed"],
  "크롭": ["crop"],
  "크리켓": ["cricket"],
  "클라우드": ["icloud"],
  "클라이밍": ["climbing"],
  "클립보드": ["clipboard"],
  "키보드": ["keyboard"],
  "킥복싱": ["kickboxing"],
  "楕円": ["ellipse"],
  "타원": ["ellipse"],
  "타이머": ["timer"],
  "타이트": ["formfitting"],
  "탁구": ["figure.table.tennis", "table", "table.tennis"],
  "卓球": ["table"],
  "태극권": ["taichi"],
  "太極拳": ["taichi"],
  "太陽": ["sun"],
  "탭": ["tap"],
  "터널": ["tunnel"],
  "터치": ["tap"],
  "테니스": ["tennis"],
  "텍스트": ["text"],
  "텔레비전": ["tv"],
  "通知": ["bell"],
  "트랙": ["track"],
  "트럭": ["truck"],
  "트레이": ["tray"],
  "트레이닝": ["training"],
  "티비": ["tv"],
  "티켓": ["ticket"],
  "팁": ["tip"],
  "팁주기": ["tip"],
  "波": ["wave", "waves"],
  "파도": ["wave", "waves"],
  "파운드": ["sterlingsign"],
  "파이프": ["pipe"],
  "파일": ["doc"],
  "파티": ["party", "popper"],
  "파형": ["waveform"],
  "波形": ["waveform"],
  "팔레트": ["paintpalette"],
  "패스": ["pass"],
  "팬": ["fan", "pan"],
  "퍼센트": ["percent"],
  "페이지": ["pages"],
  "펜싱": ["fencing"],
  "편지": ["envelope"],
  "폐": ["lungs"],
  "肺": ["lungs"],
  "閉じる": ["closed", "xmark"],
  "포인트": ["point"],
  "폭우": ["heavyrain"],
  "폭죽": ["popper"],
  "폴더": ["folder"],
  "풋볼": ["football"],
  "風": ["wind"],
  "풍선": ["balloon"],
  "風船": ["balloon"],
  "플러스": ["plus"],
  "피클볼": ["pickleball"],
  "피트니스": ["fitness"],
  "핀치": ["pinch"],
  "筆": ["paintbrush"],
  "필기": ["pencil", "square.and.pencil"],
  "필드": ["field"],
  "필라테스": ["pilates"],
  "하이킹": ["hiking", "mountain"],
  "하키": ["hockey"],
  "하트": ["heart"],
  "할인": ["percent"],
  "할일": ["checkmark", "list"],
  "해": ["sun"],
  "해변": ["beach"],
  "핸드볼": ["handball"],
  "햅틱": ["haptics"],
  "向かい": ["facing"],
  "헤드폰": ["headphones"],
  "헬스": ["dumbbell", "figure", "strengthtraining"],
  "헬스장": ["gym"],
  "호주식축구": ["australian"],
  "혼합": ["mixed"],
  "虹": ["rainbow"],
  "火": ["flame"],
  "환풍": ["fan"],
  "회사": ["briefcase"],
  "훈련": ["training"],
  "휴식": ["bed", "cup", "moon", "sofa"],
  "휴지통": ["trash"],
  "흉상": ["bust"],
  "乗馬": ["equestrian"],
  "亀": ["tortoise"],
  "写真": ["photo"],
  "医療": ["cross", "medical"],
  "挙手": ["raised"],
  "検索": ["magnifyingglass"],
  "歩く": ["walk"],
  "温度": ["degreesign"],
  "温度計": ["thermometer"],
  "湿度": ["humidity"],
  "稲妻": ["bolt"],
  "縄跳び": ["jumprope"],
  "聴診器": ["stethoscope"],
  "脳": ["brain"],
  "薬": ["pill", "pills"],
  "触覚": ["haptics"],
  "転倒": ["fall"],
  "AirPlay": ["airplay"],
  "Digital Crown": ["digitalcrown"],
  "iCloud": ["icloud"],
  "LED": ["led"],
  "PC": ["desktopcomputer"],
  "Vision Pro": ["vision"],
  "Watch": ["applewatch"],
  "Wi-Fi": ["wifi"],
  "アーチェリー": ["archery"],
  "アート": ["arts"],
  "アイデア": ["lightbulb"],
  "アメフト": ["american", "football"],
  "アラーム": ["alarm"],
  "いいね": ["thumbsup"],
  "インターバル": ["intervaltraining"],
  "ウェブ": ["web"],
  "ウォン": ["wonsign"],
  "エアバッグ": ["airbag"],
  "エリプティカル": ["elliptical"],
  "オージールール": ["australian"],
  "オーブン": ["oven"],
  "オイル": ["oilcan"],
  "カート": ["cart"],
  "カード": ["card", "creditcard"],
  "カーリング": ["curling"],
  "カゴ": ["basket"],
  "カップ": ["cup"],
  "カメラ": ["camera"],
  "カレンダー": ["calendar"],
  "キーボード": ["keyboard"],
  "ギター": ["guitars"],
  "キックボクシング": ["kickboxing"],
  "きらめき": ["sparkles"],
  "クールダウン": ["cooldown"],
  "クライミング": ["climbing"],
  "クラッカー": ["popper"],
  "グラフ": ["chart"],
  "クリケット": ["cricket"],
  "クリップボード": ["clipboard"],
  "ゲーム": ["gamecontroller"],
  "コート": ["sportscourt"],
  "コーヒー": ["saucer"],
  "コア": ["core"],
  "ごみ箱": ["trash"],
  "ゴミ箱": ["trash"],
  "コラム": ["columns"],
  "ゴルフ": ["golf"],
  "コンロ": ["cooktop"],
  "サービス": ["service"],
  "サーフィン": ["surfing"],
  "サッカー": ["soccer", "soccerball"],
  "シーケンス": ["sequence"],
  "シートベルト": ["seatbelt"],
  "ジム": ["gym"],
  "シャッター": ["shutter"],
  "シャワー": ["shower"],
  "スーツ": ["suit"],
  "スーツケース": ["suitcase"],
  "スカッシュ": ["squash"],
  "スキー": ["skiing"],
  "スケート": ["skating"],
  "スケートボード": ["skateboarding"],
  "スタック": ["stack"],
  "ステッパー": ["stepper"],
  "ステレオ": ["stereo"],
  "ストレッチ": ["flexibility"],
  "スノーボード": ["snowboarding"],
  "スピーカー": ["hifispeaker", "speaker"],
  "スプリンクラー": ["sprinkler"],
  "スポーツ": ["sports"],
  "セーリング": ["sailing"],
  "セキュリティ": ["shield"],
  "その他": ["ellipsis"],
  "ソファ": ["sofa"],
  "ソフトボール": ["softball"],
  "ターミナル": ["terminal"],
  "タイマー": ["timer"],
  "ダイヤ": ["diamond"],
  "タップ": ["tap"],
  "ダンス": ["dance"],
  "ダンベル": ["dumbbell"],
  "チェッカー": ["checkered"],
  "チェック": ["checkmark"],
  "チケット": ["ticket"],
  "チップ": ["tip"],
  "ディスク": ["disc"],
  "テキスト": ["plaintext", "text"],
  "テニス": ["tennis"],
  "テレビ": ["tv"],
  "ドアベル": ["doorbell"],
  "トラック": ["track", "truck"],
  "ドル": ["dollarsign"],
  "トレーニング": ["training"],
  "トレイ": ["tray"],
  "トンネル": ["tunnel"],
  "ナイフ": ["knife"],
  "ぬいぐるみ": ["teddybear"],
  "ノートPC": ["laptopcomputer"],
  "バー": ["barre"],
  "パーセント": ["percent"],
  "パーティー": ["party"],
  "ハート": ["heart"],
  "パイプ": ["pipe"],
  "バス": ["bus", "doubledecker"],
  "パス": ["pass"],
  "バスケ": ["basketball"],
  "バッグ": ["bag", "duffle"],
  "バドミントン": ["badminton"],
  "バレー": ["volleyball"],
  "パレット": ["paintpalette"],
  "ハンドボール": ["handball"],
  "ビーチ": ["beach"],
  "ピックルボール": ["pickleball"],
  "ビットコイン": ["bitcoinsign"],
  "ピラティス": ["pilates"],
  "ピン": ["mappin"],
  "ピンチ": ["pinch"],
  "プール": ["pool"],
  "ファインダー": ["viewfinder"],
  "ファン": ["fan"],
  "フィールド": ["field"],
  "フィット": ["formfitting"],
  "フィットネス": ["fitness"],
  "フェンシング": ["fencing"],
  "フォルダ": ["folder"],
  "フライパン": ["pan"],
  "プレゼント": ["gift"],
  "フロントガラス": ["windshield"],
  "ページ": ["pages"],
  "ヘイズ": ["haze"],
  "ベッド": ["bed"],
  "ヘッドホン": ["headphones"],
  "ヘルプ": ["questionmark"],
  "ポイント": ["point"],
  "ボウリング": ["bowling"],
  "ボクシング": ["boxing"],
  "ほこり": ["dust"],
  "ホッケー": ["hockey"],
  "ポンド": ["sterlingsign"],
  "マイク": ["mic", "microphone"],
  "マグ": ["mug"],
  "みぞれ": ["sleet"],
  "ミックス": ["mixed"],
  "メール": ["mail"],
  "メダル": ["medal"],
  "メッセージ": ["message"],
  "モーション": ["motion"],
  "ユーロ": ["eurosign"],
  "ヨガ": ["yoga"],
  "よくない": ["thumbsdown"],
  "ラグビー": ["rugby"],
  "ラクロス": ["lacrosse"],
  "ラケット": ["racket"],
  "ラケットボール": ["racquetball"],
  "リスト": ["list"],
  "リッチテキスト": ["richtext"],
  "リワード": ["rewards"],
  "ルーブル": ["rublesign"],
  "ルームランナー": ["treadmill"],
  "ルピー": ["indianrupeesign"],
  "レスリング": ["wrestling"],
  "レンチ": ["wrench"],
  "ローイング": ["rower", "rowing"],
  "ローリング": ["rolling"],
  "ロック": ["lock"],
  "ロッジ": ["lodge"],
  "ワイド": ["wide"],
  "ワイン": ["wineglass"],
};

const ALIAS_ENTRIES = Object.entries(CUSTOM_FLOW_ICON_SEARCH_ALIASES).sort(
  (a, b) => b[0].length - a[0].length,
);

/** 검색어를 SF Symbol 이름 매칭용 토큰으로 확장 */
export function expandCustomFlowIconSearchTokens(query: string): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const tokens = new Set<string>([q]);
  for (const [alias, english] of ALIAS_ENTRIES) {
    const aliasLower = alias.toLowerCase();
    // 부분 입력(휴지→휴지통)은 startsWith, 복합어(축구공→축구)는 query includes alias.
    // alias.includes(query)는 미식축구←축구처럼 상위어를 오염시키므로 쓰지 않는다.
    if (q.includes(aliasLower) || aliasLower.startsWith(q)) {
      for (const token of english) tokens.add(token.toLowerCase());
    }
  }
  return [...tokens];
}
