import { DEFAULT_BUILTIN_CUSTOM_FLOWS } from '../defaultPriorityCatalog';

/** dev mock seed — 히스토리·호라이즌용 카테고리 풀(기본 카탈로그 + 표준 키) */

/** 히스토리 seed에 쓰는 표준 카탈로그 키 */
export const SEED_STANDARD_CATEGORIES = [
  'water',
  'medicine',
  'vitamins',
  'fasting',
  'stretching',
  'straightenBack',
  'neckPosture',
  'posture',
  'meditation',
  'workout',
  'walking',
  'yoga',
  'sleep',
  'breathing',
  'skincare',
  'eyerest',
  'reading',
  'study',
  'planning',
  'writing',
  'language',
  'creative',
  'deepwork',
  'journal',
  'pomodoro',
  'review',
  'news',
  'organize',
  'podcast',
  'inbox',
  'work',
  'coding',
] as const;

export const SEED_CATEGORY_POOL = [
  ...SEED_STANDARD_CATEGORIES,
  ...DEFAULT_BUILTIN_CUSTOM_FLOWS.map((f) => f.id),
] as const;

export const SEED_CATEGORY_LABEL_KO: Record<string, string> = {
  water: '수분섭취',
  medicine: '약 복용',
  vitamins: '영양제 챙기기',
  fasting: '체중관리',
  stretching: '스트레칭',
  straightenBack: '허리펴기',
  neckPosture: '거북목 바르게하기',
  posture: '자세 교정',
  meditation: '명상',
  workout: '운동',
  walking: '산책',
  yoga: '요가',
  sleep: '수면 관리',
  breathing: '호흡 운동',
  skincare: '피부 관리',
  eyerest: '눈 휴식',
  reading: '독서',
  study: '공부·학습',
  planning: '하루·주간 정리',
  writing: '글쓰기',
  language: '언어 학습',
  creative: '창작·아이디어',
  deepwork: '딥 워크',
  journal: '일기 쓰기',
  pomodoro: '포모도로 집중',
  review: '회고·복습',
  news: '뉴스·정보 수집',
  organize: '정리정돈',
  podcast: '팟캐스트·강의',
  inbox: '메일·소통 정리',
  work: '업무 집중',
  coding: '코딩·개발',
  ...Object.fromEntries(DEFAULT_BUILTIN_CUSTOM_FLOWS.map((f) => [f.id, f.displayName])),
};
