/** 담기·루틴 탭 카탈로그에 보이는 표준 카테고리 표시명 — 단일 기준 */
export const PRIORITY_CATALOG_PICKER_LABELS: Record<string, string> = {
  water: '수분섭취',
  medicine: '약 복용',
  fasting: '체중관리',
  stretching: '스트레칭하기',
  straightenBack: '허리펴기',
  neckPosture: '거북목 바르게하기',
  meditation: '명상',
  workout: '운동',
  walking: '산책',
  yoga: '요가',
  sleep: '수면 관리',
  breathing: '호흡 운동',
  skincare: '피부 관리',
  vitamins: '영양제 챙기기',
  posture: '자세 교정',
  eyerest: '눈 휴식',
  reading: '독서',
  study: '공부·학습',
  planning: '하루·주간 정리',
  writing: '글쓰기',
  language: '언어 학습',
  creative: '창작·아이디어',
  inbox: '메일·소통 정리',
  deepwork: '딥 워크',
  journal: '일기 쓰기',
  pomodoro: '포모도로 집중',
  review: '회고·복습',
  news: '뉴스·정보 수집',
  organize: '정리정돈',
  podcast: '팟캐스트·강의',
  work: '업무 집중',
  coding: '코딩·개발',
  other: '플로우 직접 설정',
};

export function getPriorityCatalogPickerLabel(key: string): string {
  return PRIORITY_CATALOG_PICKER_LABELS[key] ?? key;
}
