/**
 * 카테고리 몰입(세션) UI — 목표 상세 설정과 동일한 라이트 에디토리얼 톤.
 * (수분: waterGoalDetailTheme 과 수치·액센트 정합)
 */
export const CategoryImmersionTheme = {
  reading: {
    screenBg: '#ffffff',
    onSurface: '#111827',
    muted: '#6b7280',
    border: '#d1d5db',
    accent: 'rgb(16, 185, 129)',
    accentText: 'rgb(52, 211, 153)',
    brand: 'LOCKFLOW READING',
    aboutKicker: 'ABOUT BOOK FLOW',
  },
  water: {
    screenBg: '#ffffff',
    onSurface: '#18181b',
    muted: '#52525b',
    border: 'rgba(0, 0, 0, 0.08)',
    accent: '#22d3ee',
    accentSoft: 'rgba(34, 211, 238, 0.14)',
    brand: 'LOCKFLOW WATER',
    aboutKicker: 'ABOUT HYDRATION',
  },
  work: {
    screenBg: '#ffffff',
    onSurface: '#18181b',
    muted: '#52525b',
    border: 'rgba(0, 0, 0, 0.08)',
    accent: 'rgb(0, 0, 0)',
    brand: 'LOCKFLOW WORK',
    aboutKicker: 'ABOUT FOCUS',
  },
  fasting: {
    screenBg: '#ffffff',
    onSurface: '#18181b',
    muted: '#52525b',
    outline: '#a1a1aa',
    border: 'rgba(0, 0, 0, 0.08)',
    accent: 'rgb(0, 0, 0)',
    brand: 'LOCKFLOW FASTING',
    aboutKicker: 'ABOUT FASTING',
  },
  medicine: {
    screenBg: '#ffffff',
    onSurface: '#18181b',
    muted: '#52525b',
    border: 'rgba(0, 0, 0, 0.08)',
    accent: 'rgb(0, 0, 0)',
    brand: 'LOCKFLOW MEDICINE',
    aboutKicker: 'ABOUT MEDICATION',
  },
  meditation: {
    screenBg: '#ffffff',
    onSurface: '#18181b',
    muted: '#52525b',
    border: 'rgba(0, 0, 0, 0.08)',
    accent: 'rgb(0, 0, 0)',
    title: '명상 세션',
  },
  yoga: {
    screenBg: '#ffffff',
    onSurface: '#18181b',
    muted: '#52525b',
    border: 'rgba(0, 0, 0, 0.08)',
    accent: 'rgb(0, 0, 0)',
    title: '요가 세션',
  },
  other: {
    screenBg: '#ffffff',
    onSurface: '#18181b',
    muted: '#52525b',
    border: 'rgba(0, 0, 0, 0.08)',
    accent: 'rgb(0, 0, 0)',
    brand: 'LOCKFLOW OTHER',
    aboutKicker: 'ABOUT TOOLS',
  },
  editorial: {
    glassBg: '#ffffff',
    glassBgAlt: 'rgba(0, 0, 0, 0.03)',
    glassBorder: 'rgba(0, 0, 0, 0.08)',
    meta: '#52525b',
    onDark: '#111827',
  },
} as const;
