import { StyleSheet } from 'react-native';

import { RETRO_BORDER_WIDTH } from '@shared/config/retroFlat';

export const orderRowStyles = StyleSheet.create({
  /** 바깥 띠(보더·세로 패딩만) — 드래그 시 잘리지 않게 flex 행은 `orderRowDragShell` */
  orderRowRoman: {
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: RETRO_BORDER_WIDTH,
  },
  /** 아이콘·제목과 액션 버튼을 한 줄로 — 리오더 시 전체가 함께 움직임 */
  orderRowDragShell: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    width: '100%',
  },
  inlineRankPill: {
    borderRadius: 0,
    borderWidth: RETRO_BORDER_WIDTH,
    borderColor: '#000000',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inlineRankPillText: {
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '800',
    letterSpacing: -0.1,
  },
  medicineIconBadge: {
    width: 20,
    height: 20,
    borderRadius: 0,
    borderWidth: RETRO_BORDER_WIDTH,
    borderColor: '#000000',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  /** 순위·아이콘·제목 — 길게 눌러 순서 변경 제스처 영역 */
  orderRowReorderMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  orderIconBoxShell: {
    position: 'relative',
    flexShrink: 0,
  },
  orderIconBoxShadow: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderRadius: 0,
  },
  orderIconBox: {
    width: 36,
    height: 36,
    borderRadius: 0,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    overflow: 'hidden',
  },
  orderRowRomanText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  orderRowTitleMark: {
    position: 'relative',
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  orderRowTitleHighlight: {
    position: 'absolute',
    left: -2,
    right: -2,
    bottom: 1,
    height: 9,
    borderRadius: 0,
    zIndex: 0,
  },
  orderRowTitleText: {
    zIndex: 1,
  },
  orderRowRomanTitle: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  orderRowRomanSubtitle: {
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: -0.1,
    lineHeight: 14,
  },
  orderRowTimeUnset: {
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: -0.1,
    lineHeight: 14,
    opacity: 0.55,
    fontStyle: 'italic',
  },
  orderRowSummaryHint: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: -0.1,
    lineHeight: 15,
  },
  subtitleTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  subtitleTimeIcon: {
    marginTop: 0.5,
  },
  orderRowRomanTitleDone: {
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
    opacity: 0.52,
  },
  orderRowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 0,
  },
  orderBrutalBtnShell: {
    position: 'relative',
  },
  orderBrutalBtnShadow: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderRadius: 0,
  },
  orderRowPriorityBtn: {
    minWidth: 26,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: '#000000',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 4,
    zIndex: 1,
    backgroundColor: '#FFFFFF',
  },
  orderRowPriorityBtnText: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: -0.2,
    lineHeight: 12,
  },
  orderSettingsBtn: {
    width: 26,
    height: 26,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    backgroundColor: '#FFFFFF',
  },
  orderFinishBtn: {
    minWidth: 26,
    height: 26,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    zIndex: 1,
    backgroundColor: '#FFFFFF',
  },
  orderFinishBtnText: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  /** 노트 스타일 아코디언 펼침 — 가로·세로 여백 최소화로 본문 풀폭 */
  expandPanel: {
    position: 'relative',
  },
  expandPanelMeasure: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 4,
    gap: 4,
  },
  expandActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 14,
    marginTop: 2,
  },
  expandActionsCol: {
    gap: 8,
    marginTop: 4,
  },
  expandNoteAction: {
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  expandNoteActionText: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: -0.2,
    lineHeight: 16,
  },
  importanceMarkBlock: {
    gap: 6,
    alignSelf: 'stretch',
  },
  importanceMarkBlockCompact: {
    gap: 4,
    paddingVertical: 2,
  },
  importanceMarkChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  importanceMarkChipShell: {
    position: 'relative',
  },
  importanceMarkChipShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 0,
  },
  importanceMarkChipFace: {
    width: '100%',
    height: '100%',
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  expandChevronBtn: {
    width: 26,
    height: 26,
    borderRadius: 0,
    borderWidth: RETRO_BORDER_WIDTH,
    borderColor: '#000000',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    zIndex: 1,
    backgroundColor: '#FFFFFF',
  },
});
